import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const wires = await prisma.product.createMany({
    data: [
      { code: 'MS-VM-0001', name: 'DJI OSMO STABILZER' },
      { code: 'MS-VM-0003', name: 'LIGHT STAND' },
      { code: 'MS-VM-0006', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0009', name: 'PHONE STAND' },
      { code: 'MS-VM-0014', name: 'AUX' },
      { code: 'MS-VM-0015', name: 'AUX' },
      { code: 'MS-VM-0016', name: 'SATA' },
      { code: 'MS-VM-0019', name: 'Network Switcher' },
      { code: 'MS-VM-0020', name: 'SATA' },
      { code: 'MS-VM-0021', name: 'MICROPHONE' },
      { code: 'MS-VM-0029', name: 'AUX' },
      { code: 'MS-VM-0030', name: 'Network Switcher' },
      { code: 'MS-VM-0033', name: 'MICROPHONE' },
      { code: 'MS-VM-0034', name: 'PHONE STAND' },
      { code: 'MS-VM-0040', name: 'Network Gateway' },
      { code: 'MS-VM-0084', name: 'ETHERNET' },
      { code: 'MS-VM-0085', name: 'ETHERNET' },
      { code: 'MS-VM-0088', name: 'Network Switcher' },
      { code: 'MS-VM-0089', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0090', name: 'Network Modem' },
      { code: 'MS-VM-0157', name: 'XLR ADAPTER' },
      { code: 'MS-VM-0397', name: 'HDMI' },
      { code: 'MS-VM-0398', name: 'POWER SUPPLY' },
      { code: 'MS-VM-0401', name: 'DISPLAY PORT' },
      { code: 'MS-VM-0403', name: 'ETHERNET' },
      { code: 'MS-VM-0404', name: 'VGA' },
      { code: 'MS-VM-0409', name: 'ETHERNET' },
      { code: 'MS-VM-0411', name: 'FIBER' },
      { code: 'MS-VM-0412', name: 'STAND' },
      { code: 'MS-VM-0416', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0417', name: 'AV' },
      { code: 'MS-VM-0419', name: 'TYPE-C' },
      { code: 'MS-VM-0424', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0426', name: 'POWER SOCKET' },
      { code: 'MS-VM-0429', name: 'ETHERNET' },
      { code: 'MS-VM-0430', name: 'POWER SOCKET' },
      { code: 'MS-VM-0431', name: 'VGA' },
      { code: 'MS-VM-0444', name: 'POWER SOCKET' },
      { code: 'MS-VM-0446', name: 'TYPE-B' },
      { code: 'MS-VM-0448', name: 'TYPE-C' },
      { code: 'MS-VM-0450', name: 'ETHERNET' },
      { code: 'MS-VM-0451', name: 'WIRELESS ROUTER' },
      { code: 'MS-VM-0455', name: 'POWER SUPPLY' },
      { code: 'MS-VM-0458', name: 'MICRO' },
      { code: 'MS-VM-0462', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0463', name: 'ETHERNET' },
      { code: 'MS-VM-0467', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0469', name: 'ETHERNET' },
      { code: 'MS-VM-0472', name: 'LED LIGHT' },
      { code: 'MS-VM-0476', name: 'ETHERNET' },
      { code: 'MS-VM-0478', name: 'ETHERNET' },
      { code: 'MS-VM-0479', name: 'ETHERNET' },
      { code: 'MS-VM-0481', name: 'SDI' },
      { code: 'MS-VM-0482', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0483', name: 'HDMI' },
      { code: 'MS-VM-0484', name: 'TYPE-C' },
      { code: 'MS-VM-0486', name: 'POWER SUPPLY' },
      { code: 'MS-VM-0487', name: 'FIBER' },
      { code: 'MS-VM-0489', name: 'SDI' },
      { code: 'MS-VM-0490', name: 'FIBER' },
      { code: 'MS-VM-0494', name: 'ETHERNET' },
      { code: 'MS-VM-0495', name: 'TYPE-C' },
      { code: 'MS-VM-0499', name: 'SDI' },
      { code: 'MS-VM-0501', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0502', name: 'ETHERNET' },
      { code: 'MS-VM-0504', name: 'STAND' },
      { code: 'MS-VM-0509', name: 'SDI' },
      { code: 'MS-VM-0512', name: 'POWER SUPPLY' },
      { code: 'MS-VM-0515', name: 'ETHERNET' },
      { code: 'MS-VM-0517', name: 'SDI' },
      { code: 'MS-VM-0521', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0526', name: 'ETHERNET' },
      { code: 'MS-VM-0527', name: 'ETHERNET' },
      { code: 'MS-VM-0529', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0532', name: 'MICRO' },
      { code: 'MS-VM-0533', name: 'ETHERNET' },
      { code: 'MS-VM-0536', name: 'POWER SOCKET' },
      { code: 'MS-VM-0538', name: 'LIGHTING' },
      { code: 'MS-VM-0539', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0542', name: 'POWER SUPPLY' },
      { code: 'MS-VM-0545', name: 'ETHERNET' },
      { code: 'MS-VM-0546', name: 'SDI' },
      { code: 'MS-VM-0550', name: 'ETHERNET' },
      { code: 'MS-VM-0551', name: 'SDI' },
      { code: 'MS-VM-0553', name: 'ETHERNET' },
      { code: 'MS-VM-0557', name: 'POWER SUPPLY' },
      { code: 'MS-VM-0561', name: 'TYPE-C' },
      { code: 'MS-VM-0563', name: 'AUX' },
      { code: 'MS-VM-0564', name: 'MICROPHONE' },
      { code: 'MS-VM-0568', name: 'Network Modem' },
      { code: 'MS-VM-0571', name: 'ETHERNET' },
      { code: 'MS-VM-0574', name: 'ETHERNET' },
      { code: 'MS-VM-0584', name: 'ETHERNET' },
      { code: 'MS-VM-0585', name: 'POWER ADAPTER' },
      { code: 'MS-VM-0586', name: 'MICRO' },
      { code: 'MS-VM-0592', name: 'MICRO' },
      { code: 'MS-VR-0001', name: 'AUDIO INTERFACE' },
      { code: 'MS-VR-0003', name: 'DISPLAY PORT' },
      { code: 'MS-VR-0004', name: 'ETHERNET' },
      { code: 'MS-VR-0006', name: 'POWER SUPPLY' },
      { code: 'MS-VR-0007', name: 'POWER ADAPTER' },
      { code: 'MS-VR-0008', name: 'HDMI' },
      { code: 'MS-VR-0010', name: 'POWER ADAPTER' },
      { code: 'MS-VR-0013', name: 'ETHERNET' },
      { code: 'MS-VR-0018', name: 'KEYBOARD' },
      { code: 'MS-VR-0020', name: 'HDMI' },
      { code: 'MS-VR-0021', name: 'KEYBOARD' },
      { code: 'MS-VR-0022', name: 'TYPE-C' },
      { code: 'MS-VR-0023', name: 'HDMI' },
      { code: 'MS-VR-0026', name: 'HDMI' },
      { code: 'MS-VR-0027', name: 'POWER ADAPTER' },
      { code: 'MS-VR-0029', name: 'ETHERNET' },
      { code: 'MS-VR-0030', name: 'POWER SUPPLY' },
      { code: 'MS-VR-0032', name: 'MICRO' },
      { code: 'MS-VR-0033', name: 'POWER ADAPTER' },
      { code: 'MS-VR-0035', name: 'ETHERNET' },
      { code: 'MS-VR-0040', name: 'TYPE-A' },
      { code: 'MS-VR-0080', name: 'MICRO' },
      { code: 'MS-VR-0081', name: 'WIFI SOCKET' },
      { code: 'MS-VR-0084', name: 'XLR ADAPTER' },
      { code: 'MS-VR-0086', name: 'STAND' },
      { code: 'MS-VR-0089', name: 'TYPE-A' },
      { code: 'MS-VR-0090', name: 'XLR' },
      { code: 'MS-VR-0095', name: 'HDMI' },
      { code: 'MS-VR-0097', name: 'MICRO' },
      { code: 'MS-VR-0098', name: 'MOUSE' },
      { code: 'MS-VR-0100', name: 'DISPLAY PORT ADAPTER' },
      { code: 'MS-VR-0101', name: 'POWER ADAPTER' },
      { code: 'MS-VR-0102', name: 'HDMI' },
      { code: 'MS-VR-0104', name: 'ETHERNET' },
      { code: 'MS-VR-0110', name: 'ETHERNET' },
    ],
  });

  console.log({ wires });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
